version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: password
    ports:
      - '6379:6379'
