// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: userkeypb/userkey.proto

package userkeypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserKeySession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyKid      string `protobuf:"bytes,1,opt,name=proxyKid,proto3" json:"proxyKid,omitempty"`
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	KeyVersion    int64  `protobuf:"varint,4,opt,name=keyVersion,proto3" json:"keyVersion,omitempty"`
	StartTime     int64  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	DurationMilli int64  `protobuf:"varint,6,opt,name=durationMilli,proto3" json:"durationMilli,omitempty"`
}

func (x *UserKeySession) Reset() {
	*x = UserKeySession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userkeypb_userkey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserKeySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKeySession) ProtoMessage() {}

func (x *UserKeySession) ProtoReflect() protoreflect.Message {
	mi := &file_userkeypb_userkey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKeySession.ProtoReflect.Descriptor instead.
func (*UserKeySession) Descriptor() ([]byte, []int) {
	return file_userkeypb_userkey_proto_rawDescGZIP(), []int{0}
}

func (x *UserKeySession) GetProxyKid() string {
	if x != nil {
		return x.ProxyKid
	}
	return ""
}

func (x *UserKeySession) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserKeySession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserKeySession) GetKeyVersion() int64 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *UserKeySession) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UserKeySession) GetDurationMilli() int64 {
	if x != nil {
		return x.DurationMilli
	}
	return 0
}

type UserKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyBase64 string `protobuf:"bytes,1,opt,name=keyBase64,proto3" json:"keyBase64,omitempty"`
}

func (x *UserKey) Reset() {
	*x = UserKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userkeypb_userkey_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKey) ProtoMessage() {}

func (x *UserKey) ProtoReflect() protoreflect.Message {
	mi := &file_userkeypb_userkey_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKey.ProtoReflect.Descriptor instead.
func (*UserKey) Descriptor() ([]byte, []int) {
	return file_userkeypb_userkey_proto_rawDescGZIP(), []int{1}
}

func (x *UserKey) GetKeyBase64() string {
	if x != nil {
		return x.KeyBase64
	}
	return ""
}

var File_userkeypb_userkey_proto protoreflect.FileDescriptor

var file_userkeypb_userkey_proto_rawDesc = []byte{
	0x0a, 0x17, 0x75, 0x73, 0x65, 0x72, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x4b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x4b, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6b, 0x65, 0x79, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x22, 0x27, 0x0a, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x42, 0x61, 0x73, 0x65,
	0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x42, 0x61, 0x73,
	0x65, 0x36, 0x34, 0x32, 0x42, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x46,
	0x72, 0x6f, 0x6d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x08, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0x00, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x62, 0x65, 0x6e, 0x6b, 0x65, 0x6e, 0x6f, 0x62, 0x69,
	0x2f, 0x63, 0x79, 0x70, 0x68, 0x65, 0x72, 0x2d, 0x6c, 0x6f, 0x67, 0x2f, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userkeypb_userkey_proto_rawDescOnce sync.Once
	file_userkeypb_userkey_proto_rawDescData = file_userkeypb_userkey_proto_rawDesc
)

func file_userkeypb_userkey_proto_rawDescGZIP() []byte {
	file_userkeypb_userkey_proto_rawDescOnce.Do(func() {
		file_userkeypb_userkey_proto_rawDescData = protoimpl.X.CompressGZIP(file_userkeypb_userkey_proto_rawDescData)
	})
	return file_userkeypb_userkey_proto_rawDescData
}

var file_userkeypb_userkey_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_userkeypb_userkey_proto_goTypes = []interface{}{
	(*UserKeySession)(nil), // 0: UserKeySession
	(*UserKey)(nil),        // 1: UserKey
}
var file_userkeypb_userkey_proto_depIdxs = []int32{
	0, // 0: UserKeyService.GetKeyFromSession:input_type -> UserKeySession
	1, // 1: UserKeyService.GetKeyFromSession:output_type -> UserKey
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userkeypb_userkey_proto_init() }
func file_userkeypb_userkey_proto_init() {
	if File_userkeypb_userkey_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userkeypb_userkey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserKeySession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userkeypb_userkey_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userkeypb_userkey_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userkeypb_userkey_proto_goTypes,
		DependencyIndexes: file_userkeypb_userkey_proto_depIdxs,
		MessageInfos:      file_userkeypb_userkey_proto_msgTypes,
	}.Build()
	File_userkeypb_userkey_proto = out.File
	file_userkeypb_userkey_proto_rawDesc = nil
	file_userkeypb_userkey_proto_goTypes = nil
	file_userkeypb_userkey_proto_depIdxs = nil
}
