package apperrors

const ErrCodeReqQueryRequired = "ReqQueryRequired"
const ErrCodeReqQueryIntParseFail = "ReqQueryIntParseFail"
const ErrCodeReqQuerySortParseFail = "ReqQuerySortParseFail"
const ErrCodeReqResourcesNotFound = "ReqItemsNotFound"
const ErrCodeCannotBindJson = "CannotBindJson"
const ErrCodeResourceAlreadyCreated = "ResourceAlreadyCreated"
const ErrCodeUsernameTaken = "UsernameTaken"
const ErrCodeUserRequireFail = "UserRequireFail"
const ErrCodeIncorrectPasscode = "IncorrectPasscode"
const ErrCodeInvalidSession = "InvalidSession"
const ErrCodeDataRace = "DataRace"
const ErrCodeMustSortByOneOption = "MustSortByOneOption"
const ErrCodeInvalidSortOptions = "InvalidSortOptions"
